int aislower (int c);
int aisupper(int c);
int aisdight(int c);
int aisalnum(int c);
int aisalpha(int c);
int aiscntrl(int c);
int aisgraph(int c);
int aispunct(int c);
int aisspace(int c);
int aisascii(int c);
int aisblank(int c);
int aisxdight(int c);
int astrlen(char *s);
int atoupper(int c);
int aisspace(int c);
int atolower(int c);
int astrcmp(char *s1, char *s2);
int astrncmp(char *s1, char *s2, int c);
int astrcasecmp(char *s1, char *s2);

